version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: pullzzz/foodgram_backend
    env_file: ./.env
    volumes:
      - ./data/:/app/data
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: pullzzz/foodgram_frontend
    volumes:
      - static:/app/result_build/build/
  nginx:
    image: pullzzz/foodgram_nginx
    ports:
      - "9002:80"
    volumes:
      - ./docs/:/var/www/html/api/docs/
      - static:/var/www/html/
      - media:/var/www/media/
    depends_on:
      - backend
