# Generated by Django 4.2.4 on 2023-08-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='ingredient',
            field=models.ManyToManyField(related_name='shopingcart', through='recipes.ShopingCartIngredient', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
