# Generated by Django 4.2.4 on 2023-09-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient_and_unit',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_ingredient_in_recipe',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient_and_unit', violation_error_message='У ингредиента может быть только однаединица измерения'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_in_recipe', violation_error_message='Ингредиент может бытьдобавлен в рецепт только один раз'),
        ),
    ]
