# Generated by Django 4.2.4 on 2023-08-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_shopingcart_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
