# Generated by Django 4.2.4 on 2023-09-20 12:23

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='recipes_allready_in_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='recipes_allready_in_shoppingcart',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[recipes.validators.RecipeNameValidator()], verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_already_in_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_already_in_shoppingcart'),
        ),
    ]
